---
title: "RHI"
author: "Pawe³ Motyka"
date: "5 marca 2018"
output: html_document
---

Preprocessing data

```{r}

library(plyr)
library(gdata)
library(BayesFactor)
library(ggplot2)
library(scales)

data_dir <- 'N:/RHI_data'
setwd(data_dir)

data <- read.table("RHI_proprioception.TXT", header = TRUE, sep = ",", fill = TRUE, stringsAsFactors = FALSE)
data_RHI <- read.table("RHI_data.csv", header = TRUE, sep = ";", fill = TRUE, stringsAsFactors = FALSE)
data_RHI <- data_RHI[,c(-17:-19)]

data <- rename(data, replace = c("IDPacjenta" = "ID"))
data <- rename(data, replace = c("IDPozycji" = "Nr"))
data <- rename(data, replace = c("NrBadania" = "Examination_nr"))
data <- rename(data, replace = c("RodzajBadaniaNr" = "Examination_type_nr"))
data <- rename(data, replace = c("RodzajBadaniaTekst" = "Task_type"))
data <- rename(data, replace = c("DataBadania" = "Date"))
data <- rename(data, replace = c("WZadane" = "target"))
data <- rename(data, replace = c("WOdczyt" = "performed"))
data <- data[,c(-9:-13)]

#rename(data, replace(c("0dwiedzenie", "Zgiêcie"), c(1,0)))
data$Task_type <- revalue(data$Task_type, c("Odwiedzenie"="abduction", "Zgiêcie"= "flexion"))

# classify as a correct rejection in case of the catch trial and "no" response
data$target_class[data$target > 45 & data$target < 75] <- "60"
data$target_class[data$target > 75 & data$target < 105] <- "90"
data$target_class[data$target > 105 & data$target < 135] <- "120"

# save response class variable as a factor
data$target_class <- factor(data$target_class)

# 30 responses per ID - check
count(data,c('ID'))

count(data$target_class == "60")
count(data$target_class == "90")
count(data$target_class == "120")

# Define main variable - Difference between target position and reproduced(performed) position
data$diff <- data$target - data$performed
data$diff_abs <- abs(data$target - data$performed)

```

Calculate variables for indviduals

```{r}


data_ID <- data.frame(ID = integer(0),
                      diff_M= numeric(0),
                      diff_M_abs = numeric(0),
                      diff_Me = numeric(0),
                      diff_Me_abs = numeric(0),
                      diff_SD = numeric(0),
                      diff_M_Ab = numeric(0),
                      diff_M_abs_Ab = numeric(0),
                      diff_Me_Ab = numeric(0),
                      diff_Me_abs_Ab = numeric(0),
                      diff_SD_Ab = numeric(0),
                      diff_M_Fl = numeric(0),
                      diff_M_abs_Fl = numeric(0),
                      diff_Me_Fl = numeric(0),
                      diff_Me_abs_Fl = numeric(0),
                      diff_SD_Fl = numeric(0),
                      diff_M_abs_60_Ab = numeric(0),
                      diff_M_abs_90_Ab = numeric(0),
                      diff_M_abs_120_Ab = numeric(0),
                      diff_SD_60_Ab = numeric(0),
                      diff_SD_90_Ab = numeric(0),
                      diff_SD_120_Ab = numeric(0),
                      diff_M_abs_60_Fl = numeric(0),
                      diff_M_abs_90_Fl = numeric(0),
                      diff_M_abs_120_Fl = numeric(0),
                      diff_SD_60_Fl = numeric(0),
                      diff_SD_90_Fl = numeric(0),
                      diff_SD_120_Fl = numeric(0))


# extract the list of participants
ID_list <- unique(data$ID)

for (p in ID_list) { # LOOP PARTICIPANTS (p)
  
 # general measures  
  
 diff_M <- mean(data$diff[data$ID == p])
 diff_M_abs <- mean(data$diff_abs[data$ID == p])
  
 diff_Me <- median(data$diff[data$ID == p])
 diff_Me_abs <- median(data$diff_abs[data$ID == p])
 
 diff_SD <- sd(data$diff[data$ID == p])
 
 
 # same measures for abduction only
 
 diff_M_Ab <- mean(data$diff[data$ID == p & data$Task_type == "abduction"])
 diff_M_abs_Ab <- mean(data$diff_abs[data$ID == p & data$Task_type == "abduction"])
  
 diff_Me_Ab <- median(data$diff[data$ID == p & data$Task_type == "abduction"])
 diff_Me_abs_Ab <- median(data$diff_abs[data$ID == p & data$Task_type == "abduction"])
 
 diff_SD_Ab <- sd(data$diff[data$ID == p & data$Task_type == "abduction"])
 
 # same measures for flexion only
 
 diff_M_Fl <- mean(data$diff[data$ID == p & data$Task_type == "flexion"])
 diff_M_abs_Fl <- mean(data$diff_abs[data$ID == p & data$Task_type == "flexion"])
  
 diff_Me_Fl <- median(data$diff[data$ID == p & data$Task_type == "flexion"])
 diff_Me_abs_Fl <- median(data$diff_abs[data$ID == p & data$Task_type == "flexion"])
 
 diff_SD_Fl <- sd(data$diff[data$ID == p & data$Task_type == "flexion"])
 
 
 # Difference and variance for target positions (60, 90, 120)
 
    # Abduction
 
    diff_M_abs_60_Ab <- mean(data$diff_abs[data$ID == p & data$target_class == "60" & data$Task_type == "abduction"]) 
    diff_M_abs_90_Ab <- mean(data$diff_abs[data$ID == p & data$target_class == "90" & data$Task_type == "abduction"])
    diff_M_abs_120_Ab <- mean(data$diff_abs[data$ID == p & data$target_class == "120" & data$Task_type == "abduction"])
    
    diff_SD_60_Ab <- sd(data$diff[data$ID == p & data$target_class == "60" & data$Task_type == "abduction"]) 
    diff_SD_90_Ab <- sd(data$diff[data$ID == p & data$target_class == "90" & data$Task_type == "abduction"])
    diff_SD_120_Ab <- sd(data$diff[data$ID == p & data$target_class == "120" & data$Task_type == "abduction"])
    
 
    # Flexion
 
    diff_M_abs_60_Fl <- mean(data$diff_abs[data$ID == p & data$target_class == "60" & data$Task_type == "flexion"]) 
    diff_M_abs_90_Fl <- mean(data$diff_abs[data$ID == p & data$target_class == "90" & data$Task_type == "flexion"])
    diff_M_abs_120_Fl <- mean(data$diff_abs[data$ID == p & data$target_class == "120" & data$Task_type == "flexion"])
    
    diff_SD_60_Fl <- sd(data$diff[data$ID == p & data$target_class == "60" & data$Task_type == "flexion"]) 
    diff_SD_90_Fl <- sd(data$diff[data$ID == p & data$target_class == "90" & data$Task_type == "flexion"])
    diff_SD_120_Fl <- sd(data$diff[data$ID == p & data$target_class == "120" & data$Task_type == "flexion"])
    
 
      
    # Create data frame with number of valid ECG events - introduced for controlling purposes
    data_ID[nrow(data_ID)+1,] <- c(p,diff_M,diff_M_abs, diff_Me, diff_Me_abs, diff_SD, diff_M_Ab, diff_M_abs_Ab, diff_Me_Ab, diff_Me_abs_Ab, diff_SD_Ab, diff_M_Fl, diff_M_abs_Fl, diff_Me_Fl, diff_Me_abs_Fl, diff_SD_Fl, diff_M_abs_60_Ab, diff_M_abs_90_Ab, diff_M_abs_120_Ab, diff_SD_60_Ab, diff_SD_90_Ab, diff_SD_120_Ab, diff_M_abs_60_Fl, diff_M_abs_90_Fl, diff_M_abs_120_Fl, diff_SD_60_Fl, diff_SD_90_Fl, diff_SD_120_Fl)

} # END: LOOP PARTICIPANTS (p)


# normalized difference _ ID 32 outlayer
data_ID$diff_Z <- (data_ID$diff_M_abs - mean(data_ID$diff_M_abs))/sd(data_ID$diff_M_abs)
hist(data_ID$diff_Z)


# third standard deviation in proprioception (remove)
data_ID <- data_ID[data_ID$ID!=32,]



```

Behavioral data exploration

```{r}

hist(data_ID$diff_M, xlim = range(-13,13))
hist(data_ID$diff_M_abs, breaks = 10)

hist(data_ID$diff_Me, xlim = range(-13,13))
hist(data_ID$diff_Me_abs, breaks = 10)

hist(data_ID$diff_SD)

t.test(data_ID$diff_M_abs_Ab, data_ID$diff_M_abs_Fl, paired = T)
boxplot(data_ID$diff_M_abs_Ab, data_ID$diff_M_abs_Fl)

loess.smooth(data_ID$diff_M_abs, data_ID$diff_SD)

cor.test(data_ID$diff_M_abs, data_ID$diff_SD, method = "spearman")
cor.test(data_ID$diff_M_abs, data_ID$diff_SD)

cor.test(data_ID$diff_M_abs_Ab, data_ID$diff_M_abs_Fl)
scatter.smooth(data_ID$diff_M_abs_Ab, data_ID$diff_M_abs_Fl)

cor.test(data_ID$diff_M_abs, data_ID$diff_SD)
cor.test(data_ID$diff_M_abs_Ab, data_ID$diff_SD)
cor.test(data_ID$diff_M_abs_Fl, data_ID$diff_SD)

scatter.smooth(data_ID$diff_M_abs, data_ID$diff_SD, xlab = "Accuracy", ylab = "Variance", main = "Proprioception assessment", cex.lab = 1.2, cex = 1.2, col = "grey6", lwd = 1.5, pch = 1)

fig1 <- ggplot(data = data_ID, aes(x = diff_M_abs, y = diff_SD)) + geom_smooth(col = "grey8", method = "lm", level=0.95, alpha = 0.7) + geom_point(col = "grey 15") + labs(x = "Accuracy  \n (expressed in degrees)" , y = "Variance") + scale_fill_manual() + theme_classic() +  ggtitle("Proprioception assessment") + theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 18), axis.text=element_text(size=16), axis.title=element_text(size=16,face="bold"))

fig1


fig1 <- ggplot(data = data_ID, aes(x = diff_M_abs, y = diff_SD)) + geom_smooth(col = "grey8", method = "lm", level=0.95, alpha = 0.7) + geom_point(col = "grey 15") + labs(x = "Mean reproduction error in degrees" , y = "Variance of the errors") + scale_fill_manual() + theme_classic() +  ggtitle("Proprioception assessment") + theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 18), axis.text=element_text(size=16), axis.title=element_text(size=16,face="bold"))

fig1




#data_ID$precision <- rescale(data_ID$diff_SD, to = c(1,0))
#scatter.smooth(data_ID$diff_M_abs, data_ID$precision, xlab = "Accuracy", ylab = "Precision", main = #"Proprioception assessment", cex.lab = 1.2, cex = 1.2, col = "grey6", lwd = 1.5, pch = 1)

```

BASIC FREQUENTIST ANALYSIS

```{r}

# Merging proprioceptive data with Rubber Hand Illusion data
d <- merge(data_ID, data_RHI, by = 'ID')

# participants data
mean(d$age)
sd(d$age)
count(d$sex[d$sex=="K"])
count(d$Gr[d$Gr=="F"])

#write.table(d, file = "RHI_data", sep = "\t")
#write.csv(d, file = "RHI_d")
#require(foreign)
#d <- format(d, digits = 4)
#write.foreign(d, "RHI_data.txt", "RHI_data.sps",   package="SPSS")

#  Create variables that summarize RHI effect (average from 3 questions)

d$str_syn <- (d$Q1_syn + d$Q2_syn + d$Q3_syn)/3
d$str_asyn <- (d$Q1_asyn + d$Q2_asyn + d$Q3_asyn)/3
d$diff_synasyn <- d$str_syn - d$str_asyn



d$Gr <- factor(d$Gr)
t.test(str_syn ~ Gr, data = d)


cor.test(d$diff_M_abs, d$str_syn)
cor.test(d$diff_M_abs, d$diff_synasyn)

cor.test(d$diff_M, d$str_syn)

cor.test(d$diff_Z, d$str_syn)

#t.test(d$str_syn[d$Gr=="C"], d$str_syn[d$Gr=="F"])


     
  
```

BAYESIAN ANALYSIS

```{r}


# BAYESIAN ANALYSIS FOR NULL EFFECTS - http://bayesfactorpcl.r-forge.r-project.org/


ttestBF(d$str_syn[d$Gr=="C"], d$str_syn[d$Gr=="F"])

bf = ttestBF(formula = str_syn ~ Gr, data = d)
bf


  
a <- lm(d$str_syn ~ d$Gr + d$diff_M_abs)
summary(a)

bf <- regressionBF(str_syn ~ Gr + diff_M_abs, data = d)
plot(bf)

bf <- regressionBF(str_syn ~ Gr + diff_M_abs + Gr:diff_M_abs, data = d)
plot(bf)

################# proper

x <- lm(str_syn ~ Gr + diff_M_abs + Gr:diff_M_abs, data = d)
summary(x)


Full <- lmBF(str_syn ~ Gr + diff_M_abs + Gr:diff_M_abs, data = d)
noInteraction <- lmBF(str_syn ~  Gr + diff_M_abs, data = d)
onlydiff <- lmBF(str_syn ~ diff_M_abs, data=d)
onlyGr <- lmBF(str_syn ~ Gr, data=d)
onlyVar <- lmBF(str_syn ~ diff_SD, data=d)

plot(Full)

allBFs <- c(Full,noInteraction,onlydiff, onlyGr)

plot(allBFs)

#these are exemplary values for now (we will take them from allBFs Object in the end)
#BFs <- c(0.060, 0.096, 0.293, 0.328)

BFs <- c(0.328, 0.293, 0.096, 0.061)

#names(a) <- c("Condition (F/C) + P. Accuracy + interaction ", "Condition (F/C) + P. Accuracy ", "P. Accuracy", "Condition (F/C)")

#names(a) <- c("C", "Co", "P. u", "Conio)")

 
barplot(BFs, main= "Regression Models for the Illusion Strength", horiz = T, xlim = c(0,1.4), xlab = "Bayes Factor", col = "grey45" , cex.lab = 1.4, cex.main = 1.4)
abline(v= 0.3, col = "black", lty = 5, lwd = 2)
abline(v = 1, col = "black", lty = 5, lwd = 2)    


barplot(a, main= "Models comparison", horiz = T, xlim = c(0,3.2), las = 0.3, xlab = "Bayes Factor", col = "grey45" , cex.lab = 1.3, xaxt = "n", font = 2)
axis(1, at=c(0,0.3,1,3), labels = T)
abline(v=0.3, col = "black", lty = 2, lwd = 2.3)
abline(v = 1, col = "black", lty = 2, lwd = 2.3)    


#### COMPUTE PRECISION LIKE CONSECUTIVE HRVs


#inaczej mierzony

Full <- lmBF(diff_synasyn ~ Gr + diff_M_abs + Gr:diff_M_abs, data = d)
noInteraction <- lmBF(diff_synasyn ~  Gr + diff_M_abs, data = d)
onlydiff <- lmBF(diff_synasyn ~ diff_M_abs, data=d)
onlyGr <- lmBF(diff_synasyn ~ Gr, data=d)
onlyVar <- lmBF(diff_synasyn ~ diff_SD, data=d)

plot(Full)

allBFs <- c(Full,noInteraction,onlydiff, onlyGr)

## !! https://plot.ly/r/3d-surface-plots/
```

